### ISSUE TITLE
Upgrade the Flutter embedding to V2

### ISSUE THREAD

**Issue by MrCsabaToth** [keysking/k_ble_peripheral#3]
V1 embedding is deprecated

**Comment by keysking** [comment]
Sorry, I haven't used flutter for a while and I'm a bit rusty. After my inspection, it seems that this plugin is using the v2.Can you help me to check again?

**Comment by MrCsabaToth** [comment]
I'm sorry, you are right. What caught me is that I received errors that the "char/create", "service/create" and other commands were not handled in the `onMethodCall`. This was a brain fart on my end.
